apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/surangajayalath/gitops.git   # Your GitHub repo
    targetRevision: main                                      # branch
    path: argo-apps                                           # folder containing child apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
