apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: support-kyverno
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  project: default
  source:
    path: "apps/charts/kyverno"
    repoURL: "https://github.com/surangajayalath/gitops.git"
    targetRevision: main
    helm:
      valueFiles:
        - "values.yaml"
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
