apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyverno/kyverno.git
    targetRevision: main
    path: config/release
    directory:
      recurse: true
      include: crds.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
