apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: support-chart-prjj
  namespace: argocd
spec:
  sourceRepos: ['*']
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
