
global:
  architecture: standalone   # or "replication"
  auth:
    enabled: true
    password: mysecretpassword  # set your own password

fullnameOverride: "redis-server-dev"

commonLabels: 
  app.kubernetes.io/instance: my-redis-server-dev
  
master:
  count: 2
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 6379
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 1

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 1
