spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/surangajayalath/gitops.git'
    targetRevision: main
    path: "apps"
metadata:
  namespace: kyverno
  project: default
  
